name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]  # Change these to match your repo branches
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read  # Allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4  # Fetch the repo before analysis

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Ensure this is set in GitHub Secrets
        with:
          args: >
            -Dsonar.projectKey=your_project_key
            -Dsonar.organization=your_organization
